server:
  port: 9090

spring:
  application:
    name: gateway-zuul
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
zuul:
  routes:
    user-service:
      path: /user/**
      serviceId: user-service
    message-service:
      path: /message/**
      serviceId: message-service
    other:
      path: /baidu/**
      url: http://www.baidu.com

user-service:
  ribbon:
    listOfServers: localhost:9070,localhost:9072

message-service:
  ribbon:
    listOfServers: localhost:9071

management:
  endpoints:
    web:
      exposure:
        include: "*"

#ribbon:
#  restclient:
#    enabled: true
#  ReadTimeout: 60000
#  ConnectTimeout: 60000

#hystrix:
#  command:
#    default:
#      execution:
#        isolation:
#          thread:
#            timeoutInMilliseconds: 60000

#eureka:
#  client.:
#    register-with-eureka: false
#    fetch-registry: false

